application: bowling-4
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  secure: always  

- url: /.*
  script: games.wsgi.application
  secure: always

libraries:
- name: MySQLdb
  version: latest

- name: django
  version: "1.5"

- name: ssl
  version: latest

builtins:
- django_wsgi: on
